vich_uploader:
    db_driver: orm

    mappings:
        challenge_image:
            uri_prefix: /assets/images/challenges
            upload_destination: '%kernel.project_dir%/public/assets/images/challenges'
            namer: vich_uploader.namer_uniqid
        accueil_image:
            uri_prefix: /assets/images
            upload_destination: '%kernel.project_dir%/public/assets/images'
            namer: vich_uploader.namer_uniqid

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
